# Generated by Django 5.2.18 on 2026-10-09 15:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('horarios', models.TextField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('BAJA', 'Dada de baja')], default='ACTIVA', max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='sede_nombre_unico_sin_mayusculas')],
            },
        ),
    ]
